config/routes.rb
Rails.application.routes.draw do
  get 'map_layers/index'
  root 'map_layers#index'

  resources :characters

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assist.rb
class Assist < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true

  def weapon_name=(name)
    self.weapon_id = Weapon.find_by_name(name).id
  end
  def assist_name=(name)
    self.assist_id = Assist.find_by_name(name).id
  end
  def special_name=(name)
    self.special_id = Special.find_by_name(name).id
  end
  def skill_a_name=(name)
    self.skill_a_id = SkillA.find_by_name(name).id
  end
  def skill_b_name=(name)
    self.skill_b_id = SkillB.find_by_name(name).id
  end
  def skill_c_name=(name)
    self.skill_c_id = SkillC.find_by_name(name).id
  end
end

app/models/combat_phase.rb
class CombatPhase < ApplicationRecord
end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/map_tile_ids.rb
class MapTileIds
  @@map_tile_ids = [
    ["tile11", "tile12", "tile13", "tile14", "tile15", "tile16"],
    ["tile21", "tile22", "tile23", "tile24", "tile25", "tile26"],
    ["tile31", "tile32", "tile33", "tile34", "tile35", "tile36"],
    ["tile41", "tile42", "tile43", "tile44", "tile45", "tile46"],
    ["tile51", "tile52", "tile53", "tile54", "tile55", "tile56"],
    ["tile61", "tile62", "tile63", "tile64", "tile65", "tile66"],
    ["tile71", "tile72", "tile73", "tile74", "tile75", "tile76"],
    ["tile81", "tile82", "tile83", "tile84", "tile85", "tile86"]
  ]   
end

app/models/move_type.rb
class MoveType < ApplicationRecord
end

app/models/seal.rb
class Seal < ApplicationRecord
end

app/models/skill_a.rb
class SkillA < ApplicationRecord
  # SKILL_NAMES = %w(as kjhkh lkjlkjl lkjlkj )
  # validates :name, inclusion: { in:  }, presence: true, uniqueness: true
end

app/models/skill_b.rb
class SkillB < ApplicationRecord
end

app/models/skill_c.rb
class SkillC < ApplicationRecord
end

app/models/special.rb
class Special < ApplicationRecord
end

app/models/tile.rb
class Tile < ApplicationRecord
end

app/models/tile_type.rb
class TileType < ApplicationRecord

end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/weapon.rb
class Weapon < ApplicationRecord
end

app/models/weapon_type.rb
class WeaponType < ApplicationRecord
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to map_layers_index_url(:latestCharacterID => @character)
    end
  end

  private
    def character_params
      params.require(:character).permit(:name, :weapon_type_id, :move_type_id, :type_id, :weapon_id, :assist_id, :special_id, :skill_a_id, :skill_b_id, :skill_c_id, :seal_id, :attack, :speed, :defense, :resistance, :weapon_name, :assist_name, :special_name, :skill_a_name, :skill_b_name, :skill_c_name)
    end
end

app/controllers/map_layers_controller.rb
class MapLayersController < ApplicationController
  def index
    @map = Map.new
    @character = Character.new
    @characters = Character.all
    @types = Type.all
    @latestCharacter = Character.find(params[:latestCharacterID]) if params[:latestCharacterID] != nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/map_layers_helper.rb
module MapLayersHelper
end

app/views/map_layers/index.html.erb
 <%= stylesheet_link_tag "application" %>


<div class = "row">
  <div class = "column terrain"> <p> TODO: Terrain Column? </p> </div>
  <div class = "column map">
    <table id = "map">
      <tr>  
        <td class = "tile" id = "11"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "12"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "13"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "14"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "15"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "16"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>    
        <td class = "tile" id = "21"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "22"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "23"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "24"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "25"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "26"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>    
        <td class = "tile" id = "31"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "32"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "33"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "34"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "35"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "36"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>      
        <td class = "tile" id = "41"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "42"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "43"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "44"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "45"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "46"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>      
        <td class = "tile" id = "51"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "52"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "53"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "54"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "55"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "56"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>      
        <td class = "tile" id = "61"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "62"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "63"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "64"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "65"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "66"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>      
        <td class = "tile" id = "71"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "72"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "73"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "74"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "75"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "76"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
      <tr>
        <td class = "tile" id = "81"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "82"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "83"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "84"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "85"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
        <td class = "tile" id = "86"> 
          <%= image_tag "tiles/normal.png", class: "tileImage" %>  
        </td>
      </tr>
    </table>
  </div>  
  <div class = "column character">
    <%= form_with scope: :character, url: characters_url, local: true do |form| %>
      <div id = "characterLogisticsRow">
        <div id = "characterLogistics">
          <p>
            <%= form.label :Name %><br>
            <%= form.text_field :name, value: "New Character" %>
          </p>
          <p>
            <%= form.label "Move Type" %><br>
            <%= form.collection_select :move_type_id, MoveType.all, :id, :name %>            
          </p>
        </div>
        <div id = "characterLogistics">        
          <p>
            <%= form.label "Weapon Type" %><br>
            <%= form.collection_select :weapon_type_id, WeaponType.all, :id, :name %>            
          </p>
          <p>
            <%= form.label :Type %><br>
            <%= form.collection_select :type_id, Type.all, :id, :name %>            
          </p>
        </div>
      </div>

      <div id = "characterSkillsRow">
        <div id = "characterSkills">
          <p>
            <%= form.label :weapon_name %><br>
            <%= form.text_field :weapon_name, value: Weapon.first().name, class: :weapon_name, data: {src: Weapon.order(:name).map(&:name)} %>
          </p>
          <p>
            <%= form.label :assist_name %><br>
            <%= form.text_field :assist_name, value: Assist.first().name, class: :assist_name, data: {src: Assist.order(:name).map(&:name)} %>
          </p>
          <p>
            <%= form.label :special_name %><br>
            <%= form.text_field :special_name, value: Special.first().name, class: :special_name, data: {src: Special.order(:name).map(&:name)} %>
          </p>
          <p>
            <%= form.label :skill_a_name %><br>
            <%= form.text_field :skill_a_name, value: SkillA.first().name, class: :skill_a_name, data: {src: SkillA.order(:name).map(&:name)} %>
          </p>
          <p>
            <%= form.label :skill_b_name %><br>
            <%= form.text_field :skill_b_name, value: SkillB.first().name, class: :skill_b_name, data: {src: SkillB.order(:name).map(&:name)} %>
          </p>
          <p>
            <%= form.label :skill_c_name %><br>
            <%= form.text_field :skill_c_name, value: SkillC.first().name, class: :skill_c_name, data: {src: SkillC.order(:name).map(&:name)} %>
          </p>

          <p>
            <%= form.label :Seal %><br>
            <%= form.text_field :seal_id %>
          </p>
        </div>

        <div id = "characterSkills">
          <p>
            <%= form.label :Atk %><br>
            <%= form.text_field :attack, value: 0 %>
          </p>

          <p>
            <%= form.label :Spd %><br>
            <%= form.text_field :speed, value: 0 %>
          </p>

          <p>
            <%= form.label :Def %><br>
            <%= form.text_field :defense, value: 0 %>
          </p>

          <p>
            <%= form.label :Res %><br>
            <%= form.text_field :resistance, value: 0 %>
          </p>
        </div>
      </div>
      <p>
        <%= form.submit %>
      </p>
    <% end %>

    <% if @latestCharacter != nil %>
      <p>
        Created Character: 
        <%= @latestCharacter.name %>
        <%= image_tag "characters/test.png", class: "characterImage" %>          
      </p>
    <% end %>
  </div>
</div>

<% if false %>
<table>
  <tr>
    <th>Name</th>
    <th>Weapon</th>
    <th>Special</th>
    <th>Assist</th>
    <th>Skill A</th>
    <th>Skill B</th>
    <th>Skill C</th>
    
  </tr>

  <% @characters.each do |character| %>
    <tr>
      <td><%= character.name %></td>
      <td><%= character.weapon_id %></td>
      <td><%= character.special_id %></td>
      <td><%= character.assist_id %></td>
      <td><%= character.skill_a_id %></td>
      <td><%= character.skill_b_id %></td>
      <td><%= character.skill_c_id %></td>      
      
    </tr>
  <% end %>
</table> 
<% end %>